environment = "TST"
tag_buildby = "Anshul"
location = "UK South"
rsgNet = "rsg-uks-conn-net-prod"
rsgPatch = "rsg-uks-conn-patching-prod"
rsgStoaccount = "rsg-uks-conn-stoacc-prod"
subscription_id = "390c40ff-9a65-44fc-b4a2-698cdcda0ab5"
azure_acc_name = "aut-uks-01"
